# Generated by Django 6.0.4 on 2026-04-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HorariosDeLosturnos',
            new_name='HorarioTurno',
        ),
    ]
