# Generated by Django 6.0.4 on 2026-05-01 20:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_servicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='horarioturno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='turnos/'),
        ),
        migrations.AddField(
            model_name='horarioturno',
            name='notas',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
